### ISSUE TITLE
Missing lib： No module named 'runnable'

### ISSUE THREAD

**Issue by YY-chen555** [smthnspcl/wifuzz#1]
![image](https://user-images.githubusercontent.com/82623124/209048672-b82fde70-37d9-4472-882a-21b8830f3851.png)

**Comment by nbdy** [comment]
The latest commit should address this issue. You probably did not run `pip3 install -r requirements.txt` to install all the requirements.

You can now just run `pip3 install wifuzz` to install the tool. Afterwards you should be able to just call `wifuzz`.
